Window render and extended blood cell models
GPU-Blood-Cell-Simulation/Simulation-Server pull request #1
Opened 2023-11-21 12:56 UTC by lndl-hlaw

2023-11-22 20:51 UTC, PNieck requested changes
Trzeba naprawić nieresponsywnośc okna

2023-11-22 20:51 UTC, PNieck commented on src/main.cu
> +        shouldBeRunning = frameCount++ < maxFrames
Brak średnika

2023-11-24 13:30 UTC, HubLaw5555 commented on src/main.cu
> +        shouldBeRunning = frameCount++ < maxFrames
> Brak średnika

done

2023-11-24 13:31 UTC, HubLaw5555 commented
> Trzeba naprawić nieresponsywnośc okna

done

2023-11-24 20:12 UTC, PNieck commented
![obraz](https://github.com/GPU-Blood-Cell-Simulation/Simulation-Server/assets/99663242/d5693529-56e4-443d-a6e8-d7293ea049e8)
Taki błąd dostaje przy uruchamianiu

2023-11-24 20:30 UTC, HubLaw5555 commented
> ![obraz](https://private-user-images.githubusercontent.com/99663242/285538842-d5693529-56e4-443d-a6e8-d7293ea049e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NTcyOTksIm5iZiI6MTcwMDg1Njk5OSwicGF0aCI6Ii85OTY2MzI0Mi8yODU1Mzg4NDItZDU2OTM1MjktNTZlNC00NDNkLWE2ZTgtZDcyOTNlYTA0OWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIwMTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjOTJkZTFiNDMwMjkxMGRkNWMzNTdlNzNjOWM3ODY3MzlkM2FhZmEyY2U2MDEzMmE1Yzg4MGI1Yzk4ODU4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0SvH0nPFqrxssFhbobaoMITbMh8TT5uXQig_MI1Ksbw) Taki błąd dostaje przy uruchamianiu

dzięki za zauważenie, poprawiłem

2023-11-24 23:13 UTC, PNieck approved these changes
Poza tym, że te krwinki się rozwalają z czasem to wszystko inne powinno działać

2023-12-03 12:24 UTC, merged